#Resolución de pantalla
PANTALLA_ANCHO = 800
PANTALLA_ALTO = 600
#Colores
NEGRO =  (  0,   0,   0)
BLANCO = (255, 255, 255)
ROJO =   (255,   0,   0)
AZUL =   (  0,   0, 255)
#Detalles de sprite
TAMANIO_MOSAICO = 32
VELOCIDAD_JUGADOR = 3
VELOCIDAD_REDUCIDA = 1
VELOCIDAD_DISPARO = 4
FPS = 60
VIDA_INICIAL = 3
INTERVALO_DISPARO = 3000 #en milisegundos (3 segundos)

CAPA = [1, 2, 3]

MAPA = [
    'AAAAAAAAAAAAAAAAAAAAAAAAAWWWWWWWWWWW',
    'A...J...................AWWWWWWWWWWW',
    'AAAAAAAAAAAAAAAAAAAAA...AWWWWWWWWWWW',
    'AAAA..................8.AWWWWWWWWWWW',
    'AAAAAAA.................AWWWWWWWWWWW',
    'A6..AAA..A..A.....A.....AWWWWWWWWWWW',
    'AA...AA8A.AA.A.8.A......AWWWWWWWWWWW',
    'AAA...AAAWWWWWAAAWWWWWWWAWWWWWWWWWWW',
    'AAAA....................AWWWWWWWWWWW',
    'AAAAA...................AWWWWWWWWWWW',
    'AAAAA...................AWWWWWWWWWWW',
    'AAAAA................AAAAWWWWWWWWWWW',
    'AAAAA................WW4AWWWWWWWWWWW',
    'AAAAA............A...WW4AWWWWWWWWWWW',
    'A2.6A................AAAAWWWWWWWWWWW',
    'A...A...................AWWWWWWWWWWW',
    'AW.WA...................AWWWWWWWWWWW',
    'A.W.A.AA.AA.AAAA.AAAA...AWWWWWWWWWWW',
    'AW2WA.A.A.A.A.......A...AWWWWWWWWWWW',
    'A.W.A.A...A.AAA..A..A...AWWWWWWWWWWW',
    'AW.WA.A...A.A.....AA....AWWWWWWWWWWW',
    'A.W.A.....WWWWWWW.......AWWWWWWWWWWW',
    'AW.WA.....WWAWAWW.......AWWWWWWWWWWW',
    'A......AAAWW486WWAAA....AWWWWWWWWWWW',
    'AAAAAAAAAAAAA..AAAAAAAAAAWWWWWWWWWWW',
    'WWWWWWWWWWWWA.AWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWA.AWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWAWAWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWAWAWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWAWAWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWA8AWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWAAAWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
]