PANTALLA_ANCHO = 800
PANTALLA_ALTO = 600
FPS = 60 #Frames por segundo

TAMANIO_MOSAICO = 32

CAPA = [1, 2, 3]
#CAPA_JUGADOR = 3
#CAPA_ARBOL = 2
#CAPA_PISO = 1

VELOCIDAD_JUGADOR = 3
VELOCIDAD_ENEMIGO = 2
VIDA_INICIAL = 3

ROJO =  (255,  0,  0)
NEGRO = (  0,  0,  0)
BLANCO =(255,255,255)
AZUL =  (  0,  0,255)

MAPA = [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWWWWWWWWWWW',
    'WWWWWWWWWWWAJ...............................AWWWWWWWWWWW',
    'WWWWWWWWWWWA................................AWWWWWWWWWWW',
    'WWWWWWWWWWWA..........AAAAAA...........A....AWWWWWWWWWWW',
    'WWWWWWWWWWWA................................AWWWWWWWWWWW',
    'WWWWWWWWWWWA................................AWWWWWWWWWWW',
    'WWWWWWWWWWWA................................AWWWWWWWWWWW',
    'WWWWWWWWWWWA....A...........................AWWWWWWWWWWW',
    'WWWWWWWWWWWA................................AWWWWWWWWWWW',
    'WWWWWWWWWWWA................................AWWWWWWWWWWW',
    'WWWWWWWWWWWA........E.......................AWWWWWWWWWWW',
    'WWWWWWWWWWWA................................AWWWWWWWWWWW',
    'WWWWWWWWWWWA.....................AAA........AWWWWWWWWWWW',
    'WWWWWWWWWWWA.....................AAA........AWWWWWWWWWWW',
    'WWWWWWWWWWWA................................AWWWWWWWWWWW',
    'WWWWWWWWWWWA................................AWWWWWWWWWWW',
    'WWWWWWWWWWWA....A..................A........AWWWWWWWWWWW',
    'WWWWWWWWWWWA................................AWWWWWWWWWWW',
    'WWWWWWWWWWWA.....................E..........AWWWWWWWWWWW',
    'WWWWWWWWWWWA......AAA..............E........AWWWWWWWWWWW',
    'WWWWWWWWWWWA.......A........................AWWWWWWWWWWW',
    'WWWWWWWWWWWA................................AWWWWWWWWWWW',
    'WWWWWWWWWWWA................................AWWWWWWWWWWW',
    'WWWWWWWWWWWA..........E...........A.....A...AWWWWWWWWWWW',
    'WWWWWWWWWWWA................................AWWWWWWWWWWW',
    'WWWWWWWWWWWAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
]